### ISSUE TITLE
app crash with provided default ane

### ISSUE THREAD

**Issue by ghost** [freshplanet/ANE-Push-Notification#60]
i use the ane file provided in the bin/ folder but can't get anything right.

i publish and test my app for android, app crash either with local or distant notifications

the error i get is 

java.lang.NullPointerException
at com.freshplanet.nativeExtensions.CreateNotificationTask.onPostExecute(Unknown Source)
at com.freshplanet.nativeExtensions.CreateNotificationTask.onPostExecute(Unknown Source)
at android.os.AsyncTask.finish(AsyncTask.java:631)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:5086)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(Native Method)

i guess that has something to do with the following in the 'documentation' but don't know what to do with (which assets i should provide and how to update ?)

[quote]
If your app supports Android, you need to compile the ANE with your own assets (status bar icon etc...). To do that, use the ant build script located in the build folder (build.xml):

cd /path/to/the/ane/build
mv example.build.config build.config
edit the build.config file to provide your machine-specific paths
ant
[/quote]

otherwise my FlashDevelop project should be well configured (application.xml with the right permissions and extensionID)
i can compile it with no worry

thanks for the help

**Comment by leossmith** [comment]
i have the same problem. Please fix it :+1:

**Comment by pascomach00** [comment]
I think I managed to fix it. It works for my app.
Let me know.
https://drive.google.com/folderview?id=0B6nEmghkuTbZMWc4VGw5alp5Zms&usp=sharing

**Comment by rgerlach** [comment]
pasomach: While your ane fixed the issue of remotely sent Notifications resulting in a crash, the exception posted by pers0nal is not related to this. I see the same exception every time I do a fresh install of the app on our Samsung Galaxy S3 using Air SDK 18, without any notifications sent, just on startup.
